/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.pujigck.kotlin

data class ArrayOfNumber(val index: Int, val value: Char)

fun main() {
  val numchar = arrayOf(
        ArrayOfNumber(2, 'd'),
        ArrayOfNumber(3, 'c'),
        ArrayOfNumber(1, 'a'),
        ArrayOfNumber(5, 'b'),
        ArrayOfNumber(4, 'e')
  )
    val sortedNumchar= numchar.sortedBy{ it.index }

    for{ArrayOfNumchar in sortedNumchar}{
        println("${ArrayOfNumber.index}. ${ArrayOfNumchar.value}")
    }
}